apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      run: nginx
  template:
    metadata:
      labels:
        run: nginx
    spec:
      containers:
      - name: nginx
        image: venky2821/kubernetesimage:latest
        ports:
          - containerPort: 80
        imagePullPolicy: IfNotPresent
---
kind: Service
apiVersion: v1
metadata:
  name: nginx-svc
  #namespace: chinnu-ns
  labels:
    app: nginx
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: nginx
  type: NodePort

